### ISSUE TITLE
Can this run on IIs server with PHP?

### ISSUE THREAD

**Issue by garyfarnham** [blackbaud/sky-api-tutorial-auth-code-php#8]
I have been trying to get this auth package running on ms server 2012 with IIS and only get continuous loop from Log in, then Authorize to my application then goes bask to log in. There are no errors. I have also tried setup on local windows 10 machine with same results.
Any help much appreciated.

**Comment by Blackbaud-BobbyEarl** [comment]
Hi @garyfarnham.  Thank you for filing an issue and apologies on such a delayed response. We're now in a better position to monitor issues filed.  

I'm going to close due to inactivity, but feel free to reopen if this is still a problem.
